import { ColumnIds, Priority } from './constants.js'

export const mockTasks = [
  {
    id: 'task-1',
    title: '设计系统架构',
    description: '完成项目整体架构设计，包括前端框架选型、后端服务划分、数据库设计等核心内容。',
    tags: ['设计', '架构'],
    priority: Priority.HIGH,
    columnId: ColumnIds.TODO,
    order: 0,
    createdAt: Date.now() - 86400000 * 5,
  },
  {
    id: 'task-2',
    title: '编写用户认证模块',
    description: '实现登录、注册、密码重置等用户认证相关功能。',
    tags: ['后端', '用户系统'],
    priority: Priority.HIGH,
    columnId: ColumnIds.TODO,
    order: 1,
    createdAt: Date.now() - 86400000 * 4,
  },
  {
    id: 'task-3',
    title: '首页UI设计稿',
    description: '根据产品需求文档，设计首页的高保真UI设计稿。',
    tags: ['设计', 'UI'],
    priority: Priority.MEDIUM,
    columnId: ColumnIds.TODO,
    order: 2,
    createdAt: Date.now() - 86400000 * 3,
  },
  {
    id: 'task-4',
    title: '搭建开发环境',
    description: '完成项目开发环境的搭建，包括代码规范、CI/CD流程、本地开发服务器等。',
    tags: ['运维', '环境'],
    priority: Priority.HIGH,
    columnId: ColumnIds.IN_PROGRESS,
    order: 0,
    createdAt: Date.now() - 86400000 * 2,
  },
  {
    id: 'task-5',
    title: '用户列表页面开发',
    description: '实现用户管理的列表展示、搜索筛选、分页等功能。',
    tags: ['前端', '用户系统'],
    priority: Priority.MEDIUM,
    columnId: ColumnIds.IN_PROGRESS,
    order: 1,
    createdAt: Date.now() - 86400000 * 1,
  },
  {
    id: 'task-6',
    title: '需求评审',
    description: '与产品团队完成第一轮需求评审，明确核心功能范围。',
    tags: ['产品', '会议'],
    priority: Priority.LOW,
    columnId: ColumnIds.DONE,
    order: 0,
    createdAt: Date.now() - 86400000 * 10,
  },
  {
    id: 'task-7',
    title: '技术选型调研',
    description: '调研主流技术栈，完成技术选型报告并获得团队认可。',
    tags: ['架构', '调研'],
    priority: Priority.MEDIUM,
    columnId: ColumnIds.DONE,
    order: 1,
    createdAt: Date.now() - 86400000 * 8,
  },
  {
    id: 'task-8',
    title: '项目初始化',
    description: '创建项目仓库，配置基础目录结构和构建工具。',
    tags: ['环境', '前端'],
    priority: Priority.HIGH,
    columnId: ColumnIds.DONE,
    order: 2,
    createdAt: Date.now() - 86400000 * 7,
  },
]
